# Generated by Django 3.0.2 on 2020-06-23 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import text_miner.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filesize', models.IntegerField()),
                ('filename', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('document', models.FileField(max_length=200, upload_to=text_miner.models.user_directory_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScanPdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(max_length=1000)),
                ('category_value', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_miner.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_miner.Document')),
            ],
        ),
        migrations.CreateModel(
            name='InformationExtracted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField(max_length=100000)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_miner.Results')),
            ],
        ),
    ]
